site_name: Terraform AzureRM Provider - Contributor Guide
site_description: 'Contributor documentation and reference for the Terraform AzureRM Provider'
copyright: HashiCorp

repo_name: hashicorp/terraform-provider-azurerm
repo_url: https://github.com/hashicorp/terraform-provider-azurerm
edit_uri: "https://github.com/hashicorp/terraform-provider-azurerm/tree/main/contributing"

docs_dir: contributing
site_dir: site

nav:
  - Welcome: topics/index.md
  - Contribute:
      - Building the Provider: topics/building-the-provider.md
      - Debugging the Provider: topics/debugging-the-provider.md
  - Submit an Issue: issue-reporting-and-lifecycle.md
  - FAQ: topics/frequently-asked-questions.md

theme:
  name: material
  logo: images/hashicorp.png
  favicon: images/hashicorp-black.png
  palette:
    scheme: hashicorp
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github
  font: false
  features:
    - navigation.instant
    - content.tabs.link

plugins:
  - search:
      lang:
        - en

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: "#"

extra_css:
  - extra.css
